/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"


void
placeprog_1(char *host)
{
	CLIENT *clnt;
	readplaces_ret  *result_1;
	Place  readplace_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PLACEPROG, PLACES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = readplace_1(&readplace_1_arg, clnt);
	if (result_1 == (readplaces_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
airportprog_1(char *host)
{
	CLIENT *clnt;
	readplaces_ret  *result_1;
	Place  readairport_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, AIRPORTPROG, AIRPORTS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = readairport_1(&readairport_1_arg, clnt);
	if (result_1 == (readplaces_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	placeprog_1 (host);
	airportprog_1 (host);
exit (0);
}
