/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place_airport.h"

readplaces_ret *
readplace_1_svc(Place *argp, struct svc_req *rqstp)
{
	static readplaces_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}

readplaces_ret *
readairport_1_svc(Place *argp, struct svc_req *rqstp)
{
	static readplaces_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}
