/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "place_airport.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

Airport airport_array[NUMAIRPORTS];

void parseAirportLine(char line[100], Airport* airport)
{

  char* token = strtok(line, " \t");
  memcpy(airport->code, &token[1], sizeof(char) * 3);
  airport->code[3] = '\0';

  token = strtok(NULL, " \t");
  airport->latitude = (float)atof(token);

  token = strtok(NULL, " \t");
  airport->longitude = (float)atof(token);

  // get name and state
  token = strtok(NULL, "\t");

  // Split name and state
  char* t2 = strtok(token, ",");
  memcpy(airport->name, t2, sizeof(char) * 40);

  t2 = strtok(NULL, ",");
  memcpy(airport->state, t2, sizeof(char) * 2);
  airport->state[3] = '\0';

}

void readAirports()
{
  FILE* airports;
  Airport* new_array;
  int airport_count = 0;

  airports = fopen("airport-locations.txt", "r");
  if(airports == NULL)
  {
	printf("Opening airports failed.\n");
	return;
  }

  char line[100];
  fgets(line, 100, airports); // skip the first line of the file
  memset(line, 0, sizeof(line));
  while(airport_count < NUMAIRPORTS && fgets(line, 100, airports))
  {	  
	if(strlen(line) > 1)
	{
	  parseAirportLine(line, &airport_array[airport_count]);	  
	  airport_count++;
	}
	memset(line, 0, sizeof(line));
  }

}

static void
airportprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Place readairport_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case READAIRPORT:
		_xdr_argument = (xdrproc_t) xdr_Place;
		_xdr_result = (xdrproc_t) xdr_readplaces_ret;
		local = (char *(*)(char *, struct svc_req *)) readairport_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	readAirports();
	register SVCXPRT *transp;

	pmap_unset (AIRPORTPROG, AIRPORTS_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, AIRPORTPROG, AIRPORTS_VERS, airportprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (AIRPORTPROG, AIRPORTS_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, AIRPORTPROG, AIRPORTS_VERS, airportprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (AIRPORTPROG, AIRPORTS_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
