/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place_airport.h"

void printAirport(const Airport* airport)
{
  printf("Code:   %s\n", airport->code);
  printf("Name:   %s\n", airport->name);
  printf("State:  %s\n", airport->state);
  printf("Lat:    %f\n", airport->latitude);
  printf("Long:   %f\n", airport->longitude);
}

void
airportprog_1(char *host, Place p)
{
	CLIENT *clnt;
	readplaces_ret  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, AIRPORTPROG, AIRPORTS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = readairport_1(&p, clnt);
	if (result_1 == (readplaces_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	airportlist air = result_1->readplaces_ret_u.list;
	while(air != NULL)
	{
		printAirport(air);
		air = air->next;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	Place dummy;
	strcpy(dummy.name, "Seattle");
	strcpy(dummy.state, "WA");
	dummy.latitude = 47.626353;
	dummy.longitude = -122.333144;
	
	host = argv[1];
	airportprog_1 (host, dummy);
exit (0);
}
