/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place_airport.h"
#include <math.h>

#define pi 3.14159265358979323846

extern Airport airport_array[NUMAIRPORTS];

/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*:: This function converts decimal degrees to radians :*/
/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
double deg2rad(double deg) {
 return (deg * pi / 180);
}
/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*:: This function converts radians to decimal degrees :*/
/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
double rad2deg(double rad) {
 return (rad * 180 / pi);
}

double distance(double lat1, double lon1, double lat2, double lon2)
{
 double theta, dist;
 theta = lon1 - lon2;
 dist = sin(deg2rad(lat1)) * sin(deg2rad(lat2)) + cos(deg2rad(lat1)) *
 cos(deg2rad(lat2)) * cos(deg2rad(theta));
 dist = acos(dist);
 dist = rad2deg(dist);
 dist = dist * 60 * 1.1515;
 return (dist);
}

Airport* getNearestAirports(float latitude, float longitude)
{	
	double smallest[5] = {999999,999999,999999,999999,999999};
	Airport* closest_airports = malloc(5 * sizeof(Airport));
	int i=0;
	
	while(i<NUMAIRPORTS)
	{
		double currentDistance = distance((float)latitude, (float)longitude, (float)airport_array[i].latitude, (float)airport_array[i].longitude);
		int pos = 5;
		while(currentDistance<smallest[pos-1]&& pos>0)
			pos--;
		
		if(pos!=5)
		{
			int j;	
			for(j = 4; j > pos; j--)
			{
				closest_airports[j]=closest_airports[j-1];
				smallest[j]=smallest[j-1];
			}
			closest_airports[pos] = airport_array[i];
			//printf("%s\n", closest_airports[pos].name);
			closest_airports[pos].distance = (float)currentDistance;
			smallest[pos]= currentDistance;
		}
		i++;
	}
	int k;
	for(k = 0; k < 5; k++)
		printf("%s\n", closest_airports[k].name);
	return closest_airports;
}

readplaces_ret *
readairport_1_svc(Place *argp, struct svc_req *rqstp)
{
	static readplaces_ret  result;
	
	//airportlist air;
	//airportlist* air_list;
	Airport* airports_returned;
	airportlist curr, front = NULL;
	
	airports_returned = getNearestAirports(argp->latitude, argp->longitude);
	
	int i = 0;
	while(i<5)
	{
		curr = malloc(sizeof *curr);
		//curr->name = malloc(strlen(airports_returned[i].name)+1);
		strcpy(curr->name, airports_returned[i].name);
		//curr->state = malloc(strlen(airports_returned[i].state)+1);
		strcpy(curr->state,airports_returned[i].state);
		//curr->code = malloc(strlen(airports_returned[i].code)+1);
		strcpy(curr->code,airports_returned[i].code);
		curr->latitude = airports_returned[i].latitude;
		curr->longitude = airports_returned[i].longitude;
		curr->distance = airports_returned[i].distance;
		curr->next = front;
		front = curr;
		i++;
	}
	result.readplaces_ret_u.list = front;
	result.err = 0;
	
	/*air_list = &result.readplaces_ret_u.list;
	
	*air_list = (Airport*) malloc(sizeof(Airport));
	air = *air_list;

	strcpy(air->code, "ABC");
	strcpy(air->name, "Bloop");
	strcpy(air->state, "WA");
	air->latitude = 0.123;
	air->longitude = 0.123;
	air->next = NULL;
	result.err = 0;*/
	/*
	 * insert server code here
	 */
	
		
	 
	return &result;
}
