/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place_airport.h"

void printPlace(const Place* place)
{
  printf("\nState: %s\n", place->state);
  printf("Name:  %s\n", place->name);
  printf("Lat:   %f\n", place->latitude);
  printf("Long:  %f\n\n", place->longitude);
}

void printAirport(const Airport* airport)
{
  printf("Code:      %s\n", airport->code);
  printf("Name:      %s\n", airport->name);
  printf("State:     %s\n", airport->state);
  printf("Lat:       %f\n", airport->latitude);
  printf("Long:      %f\n", airport->longitude);
  printf("Distance:  %f\n", airport->distance);
}

void
placeprog_1(char *host, char* city, char* state)
{
	CLIENT *clnt;
	readplaces_ret  *result_1;
	Place  readplace_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PLACEPROG, PLACES_VERS, "udp");
	if (clnt == NULL) {
		printf("PLACE CLIENT FAIL");
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	memcpy(readplace_1_arg.name, &city[0], sizeof(char) * PNAMELEN);
	memcpy(readplace_1_arg.state, &state[0], sizeof(char) * STATELEN);
	readplace_1_arg.state[2] = '\0';
	readplace_1_arg.latitude = 0.0;
	readplace_1_arg.longitude = 0.0;
	readplace_1_arg.host = host;
	result_1 = readplace_1(&readplace_1_arg, clnt);
	if (result_1 == (readplaces_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	airportlist air = result_1->readplaces_ret_u.list;
	if(!air)
	{
		printf("City not found\n");
	}
	else
	{
		while(air != NULL)
		{
			printAirport(air);
			air = air->next;
		}
		xdr_free((xdrproc_t) xdr_readplaces_ret, (char*) result_1);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *city;
	char *state;
	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	city = argv[2];
	state = argv[3];
	
	placeprog_1 (host, city, state);
exit (0);
}
